apiVersion: v2
name: factory-digital-twin
description: A Helm chart for Factory Digital Twin & RL Lab
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: cassandra
    version: "9.2.9"
    repository: "https://charts.bitnami.com/bitnami"
    condition: cassandra.enabled
  - name: kafka
    version: "22.1.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
  - name: elasticsearch
    version: "19.10.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: elasticsearch.enabled
  - name: grafana
    version: "6.57.4"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: prometheus
    version: "23.1.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled