apiVersion: v1
kind: Service
metadata:
  name: factory-frontend
  namespace: factory-digital-twin
  labels:
    app: factory-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: factory-frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory-frontend
  namespace: factory-digital-twin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: factory-frontend
  template:
    metadata:
      labels:
        app: factory-frontend
    spec:
      containers:
      - name: factory-frontend
        image: factory-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: VITE_BACKEND_URL
          value: "http://factory-backend:8000"
        - name: VITE_UNITY_WS_URL
          value: "ws://unity-simulation:9000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10