apiVersion: v1
kind: Service
metadata:
  name: ray-head
  namespace: factory-digital-twin
  labels:
    app: ray-head
spec:
  ports:
  - port: 8265
    name: dashboard
  - port: 10001
    name: client
  - port: 8000
    name: serve
  selector:
    app: ray-head

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-head
  namespace: factory-digital-twin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray-head
  template:
    metadata:
      labels:
        app: ray-head
    spec:
      containers:
      - name: ray-head
        image: factory-backend:latest
        command: ["ray", "start", "--head", "--dashboard-host=0.0.0.0", "--port=10001", "--dashboard-port=8265", "--block"]
        ports:
        - containerPort: 8265
          name: dashboard
        - containerPort: 10001
          name: client
        - containerPort: 8000
          name: serve
        env:
        - name: RAY_DISABLE_IMPORT_WARNING
          value: "1"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: CASSANDRA_HOST
          value: "cassandra"
        - name: UNITY_HOST
          value: "unity-simulation"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
        volumeMounts:
        - name: ray-logs
          mountPath: /tmp/ray
        - name: experiments
          mountPath: /app/experiments
      volumes:
      - name: ray-logs
        emptyDir: {}
      - name: experiments
        persistentVolumeClaim:
          claimName: experiments-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-worker
  namespace: factory-digital-twin
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ray-worker
  template:
    metadata:
      labels:
        app: ray-worker
    spec:
      containers:
      - name: ray-worker
        image: factory-backend:latest
        command: ["ray", "start", "--address=ray-head:10001", "--block"]
        env:
        - name: RAY_DISABLE_IMPORT_WARNING
          value: "1"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: CASSANDRA_HOST
          value: "cassandra"
        - name: UNITY_HOST
          value: "unity-simulation"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: ray-logs
          mountPath: /tmp/ray
      volumes:
      - name: ray-logs
        emptyDir: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: experiments-pvc
  namespace: factory-digital-twin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: "standard"